name: "godot-ci export"
on: push

env:
  GODOT_VERSION: 3.4.2
  EXPORT_NAME: peak-platformer

jobs:
	export-linux:
	name: Linux Export
	runs-on: ubuntu-latest
	container:
		image: barichello/godot-ci:3.3.4
	steps:
	  - name: Checkout
		uses: actions/checkout@v2
		with:
			lfs: true
	  - name: Setup
		run: |
			mkdir -v -p ~/.local/share/godot/templates
			mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
	  - name: Linux Build
		run: |
			mkdir -v -p build/linux
			cd $EXPORT_NAME
			godot -v --export "Linux/X11" ../build/linux/$EXPORT_NAME.x86_64
	  - name: Upload Artifact
		uses: actions/upload-artifact@v1
		with:
			name: linux
			path: build/linux

  export-web:
	name: Web Export
	runs-on: ubuntu-latest
	container:
		image: barichello/godot-ci:3.3.4
	steps:
		- name: Checkout
		  uses: actions/checkout@v2
		  with:
			lfs: true
		- name: Setup
		  run: |
			  mkdir -v -p ~/.local/share/godot/templates
			  mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
		- name: Web Build
		run: |
		  mkdir -v -p build/web
		  cd $EXPORT_NAME
		  godot -v --export "HTML5" ../build/web/index.html
	  - name: Upload Artifact
		uses: actions/upload-artifact@v1
		with:
		  name: web
		  path: build/web
